//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 电商.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookstatus
    {
        public bookstatus()
        {
            this.bring = new HashSet<bring>();
        }
    
        public int id { get; set; }
        public int book_id { get; set; }
        public int num { get; set; }
        public string location { get; set; }
        public int bringnum { get; set; }
    
        public virtual book book { get; set; }
        public virtual ICollection<bring> bring { get; set; }
    }
}
