//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 电商.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.order = new HashSet<order>();
            this.bookstatus = new HashSet<bookstatus>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public int price { get; set; }
        public int pulish_id { get; set; }
        public int isdeal { get; set; }
    
        public virtual publish publish { get; set; }
        public virtual ICollection<order> order { get; set; }
        public virtual ICollection<bookstatus> bookstatus { get; set; }
    }
}
