//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 电商.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bring
    {
        public int id { get; set; }
        public int person_id { get; set; }
        public string bringtime { get; set; }
        public int book_id { get; set; }
        public int isreturn { get; set; }
        public string returntime { get; set; }
    
        public virtual bookstatus bookstatus { get; set; }
        public virtual person person { get; set; }
    }
}
